name: Docker-Pipeline

trigger:
- main

pool:
  name: Docker-pool

stages:
  - stage: dockr_build
    jobs:
      - job: dockerbuild
        steps:
        - task: lambda3docker@0
          inputs:
            command: 'build'
            imageBuild: 'todoui'
            
