name: Docker-Pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: dockr_build
    jobs:
      - job: dockerbuild
        steps:
        - task: lambda3docker@0
          inputs:
            command: 'build'
            imageBuild: 'todoui'
            
